#!/usr/bin/python3.7

from baseconvert import base

def is_prime(n):
  if n == 2 or n == 3: return True
  if n < 2 or n%2 == 0: return False
  if n < 9: return True
  if n%3 == 0: return False
  r = int(n**0.5)
  f = 5
  while f <= r:
    if n%f == 0: return False
    if n%(f+2) == 0: return False
    f +=6
  return True

def suma(g):
    sum = 0
    while g > 0:
        d = g%10
        g = g//10
        sum += d
    return sum

number_limit = 10000
vector = []

index = 0
for i in range(1,number_limit,1):
    if(is_prime(i)):
        index += 1
#       j = suma(suma(suma(i)))
#       vector.append([index,i,j, base(i,10,9)])
        vector.append(i)

item = 0
while item < len(vector) - 3:
#    var = vector[item] + vector[item+3]
#    print(var, end=" ")
    j = suma(suma(suma(suma(vector[item]))))
    k = base(vector[item], 10, 9, string=True)
    l = suma(suma(suma(suma(int(k)))))
    diff = vector[item+3] - vector[item]
    print("[",item+1,vector[item],k,l,diff,"]",end=" ")
#    print(j,end=" ")
    item += 1
    if item%3 == 0:
        print("")

